"""update model member

Revision ID: 3e0239f7a025
Revises: 96184d56180e
Create Date: 2024-12-15 13:49:23.588539

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3e0239f7a025'
down_revision = '96184d56180e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desa', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('rw', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('rt', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.drop_column('nama_wilayah')
        batch_op.drop_column('waktu_bergabung')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('waktu_bergabung', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('nama_wilayah', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('created_at')
        batch_op.drop_column('rt')
        batch_op.drop_column('rw')
        batch_op.drop_column('desa')

    # ### end Alembic commands ###
