"""update tipe data rt rw pada model member

Revision ID: 7b08d4c8e08a
Revises: 3e0239f7a025
Create Date: 2024-12-15 14:07:07.734803

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b08d4c8e08a'
down_revision = '3e0239f7a025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.alter_column('rw',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=3),
               existing_nullable=False)
        batch_op.alter_column('rt',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=3),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.alter_column('rt',
               existing_type=sa.String(length=3),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
        batch_op.alter_column('rw',
               existing_type=sa.String(length=3),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)

    # ### end Alembic commands ###
