"""hapus is_approved dan status pada model comment

Revision ID: 8919c2b6fe02
Revises: 7b08d4c8e08a
Create Date: 2024-12-15 14:41:06.248079

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8919c2b6fe02'
down_revision = '7b08d4c8e08a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('is_approved')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('status', mysql.ENUM('PENDING', 'APPROVED', 'REJECTED'), nullable=True))

    # ### end Alembic commands ###
