"""hapus author pada article

Revision ID: 9adaf562557b
Revises: 8919c2b6fe02
Create Date: 2024-12-15 15:07:30.479145

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9adaf562557b'
down_revision = '8919c2b6fe02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('author')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
