"""Add on delete cascade to admin_id and category_id

Revision ID: 9ec1f37a9793
Revises: 538872442913
Create Date: 2024-11-21 04:10:38.446354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ec1f37a9793'
down_revision = '538872442913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('products_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('products_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'admins', ['admin_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('products_ibfk_1', 'admins', ['admin_id'], ['id'])
        batch_op.create_foreign_key('products_ibfk_2', 'categories', ['category_id'], ['id'])

    # ### end Alembic commands ###
